[package]
name = "parsepdf"
version = "0.1.3"
authors = ["Nigel Kerr <nigel.kerr@gmail.com>"]

[dependencies]
approx="0.1.1"
lzw = "0.10.0"
inflate = "0.4.2"

[dependencies.nom]
version = "^4.0"
features = ["verbose-errors", "regexp"]

[dependencies.regex]
version = "^0.2"
