[package]
name = "parsepdf"
version = "0.2.1"
authors = ["Nigel Kerr <nigel.kerr@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.3.2"
memmap = "0.7.0"
kmpsearch = "1.0.0"
quick-error2 = "2.0.1"

[dependencies.nom]
version = "5.0.0-beta3"
