[package]
name = "parsepdf"
version = "0.2.4"
authors = ["Nigel Kerr <nigel.kerr@gmail.com>"]
edition = "2018"

[dependencies]
approx = "0.4.0"
memmap = "0.7.0"
kmpsearch = "1.0.0"
quick-error2 = "2.1.0"
lzw = "0.10.0"
inflate = "0.4.5"

[dependencies.nom]
version = "5.1.2"
