[package]
name = "parsepdf"
version = "0.1.2"
authors = ["Nigel Kerr <nigel.kerr@gmail.com>"]

[dependencies]
approx="0.1.1"

[dependencies.nom]
version = "^4.0.0"
features = ["verbose-errors", "regexp"]

[dependencies.regex]
version = "^0.2"
